site_name: dark
site_url: https://daximul.github.io/dark/
repo_name: daximul/dark
repo_url: https://github.com/daximul/dark

theme:
  name: material
  custom_dir: docs/assets/overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: fusion-dark
    primary: black
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github

extra_css:
  - assets/fusion.css

nav:
  - Home: index.md
  - Tutorials:
    - Get Started: documentation/index.md

markdown_extensions:
  - admonition
  - attr_list
  - meta
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - toc:
      permalink: true
  - pymdownx.highlight:
      guess_lang: false
